services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
      - ./logs/nginx:/var/log/nginx
    ports:
      - "8080:80"

  db:
     image: mariadb
     volumes:
       - ./data/db:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MARIADB_ROOT_PASSWORD: wordpress
       MARIADB_DATABASE: wordpress
       MARIADB_USER: wordpress
       MARIADB_PASSWORD: wordpress

  wordpress:
    depends_on:
      - nginx
      - db
    image: wordpress:latest
    volumes:
      - ./upload.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./data/html:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
